/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Owned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Owned__factory>;
    getContractFactory(
      name: "ContractAddress",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractAddress__factory>;
    getContractFactory(
      name: "IXen",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXen__factory>;
    getContractFactory(
      name: "XenWitch",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.XenWitch__factory>;

    getContractAt(
      name: "Owned",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Owned>;
    getContractAt(
      name: "ContractAddress",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractAddress>;
    getContractAt(
      name: "IXen",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IXen>;
    getContractAt(
      name: "XenWitch",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.XenWitch>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
